runtime: python37
entrypoint: gunicorn -b :$PORT main:app
env_variables:
  CLOUD_SQL_CONNECTION_NAME: fp-mysql:asia-northeast1:fp-tanamoto-db
  DB_USER: root
  DB_PASS: fashion10
  DB_NAME: sample_db
